stages:
  data-ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/interim/train_data.csv
    - data/interim/test_data.csv
  
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/interim
    - src/data/data_preprocessing.py
    outs:
    - data/preprocessed/train_preprocessed_data.csv
    - data/preprocessed/test_preprocessed_data.csv

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/preprocessed
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features/train_bow.csv
    - data/features/test_bow.csv

  model_building:
    cmd: python src/models/1.model_building.py
    deps:
    - data/features/train_bow.csv
    - src/models/1.model_building.py
    outs:
    - models/model.joblib

  model_evaluation:
    cmd: python src/models/2.evaluation.py
    deps:
    - data/features/test_bow.csv
    - models/model.joblib
    - src/models/2.evaluation.py
    metrics:
    - reports/metrics.json

    