name: CI

on: 
  push: 
    branch: 
      - master
  
  pull_request:
    branch: 
      - master

jobs: 
  linting: 
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: run flake8
        run: |
          echo "Linting Started..."
          flake8 src/data/data_ingestion.py
          flake8 src/data/data_preprocessing.py
          flake8 src/features/feature_engineering.py
          flake8 src/models/1.model_building.py
          flake8 src/models/2.evaluation.py
          flake8 src/models/3.model_registry.py
          flake8 flask_app/app.py
          echo "Linting Finished..."
  
  
  dvc: 
    needs: linting
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: run dvc
        env:
          CI: ${{ secrets.CI }}
        run: |
          python -c "import nltk; nltk.download('stopwords')"
          python -c "import nltk; nltk.download('wordnet')"
          echo "Execution dvc pipeline..."
          dvc repro  
          echo "Execution finished..."

      - name: Run model test
        if: success()
        env: 
          CI: ${{ secrets.CI }}
        run: |
          echo "Running unit tests"
          python -m unittest tests/test_model.py
          python -m unittest tests/test_app.py
          echo "Testing finished.."
      
      - name: Run app test
        if: success()
        # env: 
        #   CI: ${{ secrets.CI }}
        run: |
          echo "Running unit tests"
          python -m unittest tests/test_app.py
          echo "Testing finished.."
      
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Building docker Image
        if: success()
        run: |
          docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/mlops-doc-ci-img:v1 .
          docker run -d -p 8888:5000 --name my_container ${{secrets.DOCKER_HUB_USERNAME}}/mlops-doc-ci-img:v1
      
      - name: Wait for app to start
        run: |
          for i in {1..10}; do
            curl --fail http://0.0.0.0:8888 && break
            sleep 3
          done

      - name: Test docker Image
        if: success()
        run: |
          python -m tests/test_docker.py
      
      - name: Push docker Image
        if: success()
        run: |
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/mlops-doc-ci-img:v1

      - name: Clean up Container
        run: docker stop my-container && docker rm my-container 




      